// NOTE: Generated By hrp v4.3.0, DO NOT EDIT!
package main

import (
	"github.com/httprunner/funplugin/fungo"
)

func main() {
	fungo.Register("get_page_size", get_page_size)
	fungo.Register("GetUserAgent", GetUserAgent)
	fungo.Serve()
}
